{
 "title": "Traefik Demo",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "3s",
 "panels": [
  {
   "title": "Requests",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "rate(http_requests_total[1m])", "legendFormat": "{{app}}" }
   ]
  },
  {
   "title": "App-1 requests per second",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "rate(http_requests_total{app=\"app1\"}[1m])"
    }
   ]
  },
  {
   "title": "App-2 requests per second",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 4, "x": 4, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "rate(http_requests_total{app=\"app2\"}[1m])"
    }
   ]
  },
  {
   "title": "App-3 requests per second",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 4, "x": 8, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "rate(http_requests_total{app=\"app3\"}[1m])"
    }
   ]
  }
 ]
}