# adding HTTP routers
http:
  routers:
    load-balancin-demo: # router name
      entryPoints: # which entry points to listen
        - web
      service: load-balanced-svc # service to route traffic to
      rule: Host(`demo.local`) # routing rule

  # services definition
  services:
    load-balanced-svc:
      weighted:
        services:
          - name: app1
            weight: 1
          - name: app2
            weight: 1
          - name: app3
            weight: 1

    app1:
      loadBalancer:
        servers:
          - url: http://localhost:3001

    app2:
      loadBalancer:
        servers:
          - url: http://localhost:3002

    app3:
      loadBalancer:
        servers:
          - url: http://localhost:3003
